name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Generate changelog, tag & release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate changelog with git-cliff
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit updated changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Bump version & create tag
        id: version
        run: |
          # Extract latest version from changelog (assuming git-cliff inserts it as ## x.y.z)
          VERSION=$(grep -m 1 -oP '## \K[0-9]+\.[0-9]+\.[0-9]+' CHANGELOG.md)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          body: ${{ steps.git-cliff.outputs.content }}
          files: |
            binary_release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
